import subprocess
import os
import time
import random

def ip():
    generate = random.randint(1, 10)
    print("La IP generada automaticamente es 192.168.1.",generate)

def instalattion():
    hostname = os.system("cat /etc/hostname")
    print("\n", hostname, "\n")
    time.sleep(2)
    repositories = os.system("cat /etc/apt/sources.list")
    print("\n", repositories,"\n")
    time.sleep(2)
    os.system("sudo apt-get update -y > /dev/null")
    os.system("touch /etc/resolv.conf")
    os.system("echo '#Generated by NetworkManager' >> /etc/resolv.conf")
    os.system("echo 'nameserver 192.168.1.' >> /etc/resolv.conf")
    print("\nSe han cargado algunas configuraciones a /etc/resolv.conf")
    time.sleep(4)
    os.system("clear")
    os.system("sudo apt-get install samba smbclient krb5-config -y")
    os.system("cp /etc/samba/smb.conf /etc/samba/smb.conf.old")
    time.sleep(1)
    os.system("mv /etc/samba/smb.conf /etc/samba/smb.conf.old")
    print("\nPONER EN 'REALM' EL DOMINIO COMPLETO QUE QUEREMOS IMPLEMENTAR EN CASO QUE NO APAREZCA POR DEFECTO \n>EN 'DOMAIN' SOLO EL DOMINIO EN CASO QUE NO APAREZCA, LAS DEMAS OPCIONES SE DEJAN POR PREDETERMINADO \n<Enter>")
    time.sleep(3)
    os.system("samba-tool domain provision")
    time.sleep(2)
    #os.system("host -t SRV_ldap._tcp.")
    time.sleep(2)
    os.system("clear")
    os.system("smbclient -L localhost -U%")
    os.system("samba-tool domain level show")

def menu():
    time.sleep(1)
    print("1 -> Instalar todo por defecto (Debe cambiar algunos parametros como el nombre del equipo y la direccion IP)")
    time.sleep(1)
    print("\n2 -> Salir")
    time.sleep(1)
    option = input("\n--> ")
    if option == "1":
        instalattion()
    if option == "2":
        exit()
if __name__ == "__main__":
    menu()
